name = "card-cats"
pages_build_output_dir = "public"
compatibility_date = "2024-12-19"

[[d1_databases]]
binding = "DB"
database_name = "card-cats-db"
database_id = "305bb5f1-41c5-445d-a90f-9b154c940675"

[vars]
JWT_SECRET = "supersecretkey"